<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UseSourceLink>true</UseSourceLink>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.ejson.GlobalTool\jaytwo.ejson.GlobalTool.csproj" />
  </ItemGroup>

</Project>
