<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.1.7</VersionPrefix>
    <RepositoryUrl>https://github.com/jakegough/jaytwo.ejson</RepositoryUrl>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  
</Project>
