<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseSourceLink>true</UseSourceLink>
    <NoWarn>$(NoWarn);NU1902;NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="jaytwo.SolutionResolution" Version="0.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="Moq" Version="4.10.1" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\examples\jaytwo.ejson.example.AspNetCore3_0\jaytwo.ejson.example.AspNetCore3_0.csproj" />
  </ItemGroup>

</Project>
